//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "file_metadata")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub space_key: String,
    pub file_path: String,
    pub file_name: String,
    pub file_extension: Option<String>,
    pub file_size: Option<i64>,
    pub file_hash: Option<String>,
    pub mime_type: Option<String>,
    pub is_directory: bool,
    pub last_modified: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    pub content_preview: Option<String>,
    pub tags: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
