//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "knowledge_edge")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub from_node_id: String,
    pub to_node_id: String,
    pub relationship_type: String,
    pub weight: Option<i32>,
    pub created_at: DateTimeWithTimeZone,
    pub metadata: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
