//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "knowledge_node")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub node_id: String,
    pub node_type: String,
    pub title: Option<String>,
    pub content: Option<String>,
    pub source_file: Option<String>,
    pub source_space: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub confidence_score: Option<i32>,
    pub metadata: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
