//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::space::Entity as Space;
pub use super::repository::Entity as Repository;
pub use super::file_metadata::Entity as FileMetadata;
pub use super::knowledge_node::Entity as KnowledgeNode;
pub use super::knowledge_edge::Entity as KnowledgeEdge;
